# Site settings
title: paco[dot]org
email: contact [at] paco.org
description: I’m a member of the IT Faculty at El Centro College in the Dallas County Community College District for the Internet Development Technologies program. I currently teach Digital Imaging and Web Design classes using Adobe Photoshop and Adobe Dreamweaver, plus HTML5 and CSS3 coding. I also teach Web Project Management, Portfolio Development and WordPress courses.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://paco.org" # the base hostname & protocol for your site
twitter_username: pacodotorg 
github_username:  pacodotorg


# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

paginate:            5


# Build settings
markdown: kramdown
kramdown:
  input: GFM

# Third-party services
# just leave someone empty to disable it
# google_analytics: 
disqus_shortname:

# used this for post_excerpt at index_page
excerpt_separator: